#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH="$PATH:$HOME/.local/bin"
export WORKON_HOME=$HOME/.venvs
export PROJECT_HOME="$HOME/Documents/Development"
export VIRTUALENVWRAPPER_PYTHON=$HOME/.local/pipx/venvs/virtualenvwrapper/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=$HOME/.local/pipx/venvs/virtualenvwrapper/bin/virtualenv
source $HOME/.local/pipx/venvs/virtualenvwrapper/bin/virtualenvwrapper.sh

source_venv() {
    source $HOME/.local/pipx/venvs/virtualenvwrapper/bin/virtualenvwrapper.sh
}

gtd() {
  cd ~/documents/development
  cd $1
}

kube() {
	source <(kubectl completion zsh)
	alias k=kubectl
	complete -F __start_kubectl k
}

alias v=mkvirtualenv

