---
homebrew_packages:
  - autoconf
  - autojump
  - automake
  - brew-cask
  - coreutils
  - cowsay
  - exiftool
  - ffmpeg
  - freetype
  - gdbm
  - git
  - gpg
  - htop-osx
  - imagemagick
  - jpeg
  - jpegoptim
  - lesspipe
  - libevent
  - libmemcached
  - libpng
  - libtool
  - libyaml
  - md5sha1sum
  - memcached
  - mysql
  - node
  - openssl
  - ossp-uuid
  - percona-toolkit
  - pkg-config
  - pngcrush
  - postgresql
  - pypy
  - python
  - python3
  - readline
  - ruby
  - ruby-build
  - ruby-install
  - sloccount
  - sqlite
  - watch
  - wget
  - xz
  - youtube-dl
  - zsh-completions

homebrew_cask_packages:
  - alfred
  - anki
  - arq
  - bettertouchtool
  - boot2docker
  - calibre
  - ccleaner
  - charles
  - cheatsheet
  - disk-inventory-x
  - evernote
  - firefox
  - flux
  - google-chrome
  - karabiner
  - keyboard-maestro
  - kindle
  - mactex
  - makehuman
  - pdftk
  - pgadmin3
  - rescuetime
  - sequel-pro
  - skim
  - skype
  - soundcleod
  - steam
  - sublime-text
  - texmaker
  - utorrent
  - vagrant
  - virtualbox
  - vlc

pip_packages:
  - csvkit
  - dynamodb_utils
  - ec2-ssh
  - flake8
  - Glances
  - ipdb
  - ipython
  - numpy
  - pandas
  - pep8
  - pygments
  - requests
  - scipy
  - sh
  - six
  - Unipath
  - virtualenvwrapper
