---
homebrew_packages:
  - autoconf
  - autojump
  - automake
  - brew-cask
  - coreutils
  - cowsay
  - exiftool
  - ffmpeg
  - freetype
  - fswatch
  - gdbm
  - git
  - gpg
  - htop-osx
  - imagemagick
  - jpeg
  - jpegoptim
  - jq
  - lesspipe
  - libevent
  - libmemcached
  - libpng
  - libtool
  - libyaml
  - md5sha1sum
  - memcached
  - mysql
  - ncdu
  - node
  - openssl
  - ossp-uuid
  - percona-toolkit
  - pkg-config
  - pngcrush
  - postgresql
  - pypy
  - python
  - python3
  - readline
  - rtmpdump
  - ruby
  - ruby-build
  - ruby-install
  - sloccount
  - sqlite
  - tree
  - watch
  - wget
  - xz
  - youtube-dl
  - zsh-completions

homebrew_cask_packages:
  - alfred
  - anki
  - arq
  - bettertouchtool
  - boot2docker
  - calibre
  - disk-inventory-x
  - evernote
  - firefox
  - flux
  - google-chrome
  - karabiner
  - keyboard-maestro
  - mactex
  - pdftk
  - pgadmin3
  - rescuetime
  - sequel-pro
  - skim
  - skype
  - soundcleod
  - steam
  - sublime-text
  - texmaker
  - utorrent
  - vagrant
  - virtualbox
  - vlc

pip_packages:
  - 'git+https://github.com/adamchainz/ec2-ssh.git@master#egg=ec2-ssh'
  - 'https://bitbucket.org/adamchainz/pygments-ipython-console/get/master.zip#egg=pygments-ipython-console'
  - csvkit
  - dynamodb_utils
  - flake8
  - Glances
  - ipdb
  - ipython
  - lifelogger
  - numpy
  - pandas
  - pathlib
  - pep8
  - pygments
  - pylint
  - pythonpy
  - pyyaml
  - requests
  - scipy
  - sh
  - six
  - Unipath
  - virtualenvwrapper

npm_packages:
  - ember-cli
  - phonegap
  - vtop
