- name: zsh - git repo for prezto fork
  git: repo=git@github.com:adamchainz/prezto.git
       dest=~/.zprezto

- name: zsh - link in prezto files
  file: state=link src=~/.zprezto/runcoms/{{ item }} path=~/.{{ item }}
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv
    - zshrc
    - zpreztorc

- name: Sublime Text 3 settings
  git: repo=git@github.com:adamchainz/sublime_text_3_settings.git
       dest=~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

- name: KeyRemap4MacBook dir
  file: path="/Users/chainz/Library/Application Support/KeyRemap4MacBook/"
        state=directory

- name: KeyRemap4MacBook private.xml
  file: src=~/Documents/Projects/mac-ansible/roles/adam_mac/files/KeyRemap4MacBook_private.xml
        dest="/Users/chainz/Library/Application Support/KeyRemap4MacBook/private.xml"
        state=link
