- file: path=~/.{{ item }} state=directory
  with_items:
    - innotop
    - ssh

- file: src=~/Documents/Projects/mac-ansible/roles/adam_mac/files/dotfiles/{{ item }}
        path=~/.{{ item }}
        state=link
  with_items:
    - gitconfig
    - gitignore_global
    - python_startup
    - ssh/config
    - ansible.cfg

- copy: src=dotfiles/innotop/innotop.conf
        dest=~/.innotop/innotop.conf
        force=no  # Only if it doesn't exist

- name: zsh - git repo for prezto fork
  git: repo=git@github.com:adamchainz/prezto.git
       dest=~/.zprezto

- name: zsh - link in prezto files
  file: state=link src=~/.zprezto/runcoms/{{ item }} path=~/.{{ item }}
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv
    - zshrc
    - zpreztorc
