- name: homebrew taps
  homebrew_tap:
    tap: '{{ item }}'
  with_items: '{{ homebrew_taps }}'
  tags:
  - brew

- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
  - brew

- name: Uninstall old homebrew packages
  homebrew:
    name: '{{ item }}'
    state: absent
  with_items: '{{ homebrew_package_removals }}'
  tags:
  - brew

- name: Install homebrew packages
  homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_packages }}'
  tags:
  - brew

- name: Install homebrew cask packages
  homebrew_cask:
    name: '{{ item }}'
    state: installed
  with_items: '{{ homebrew_cask_packages }}'
  tags:
  - brew

- name: Install pip packages
  pip:
    name: '{{ item }}'
    state: latest
  with_items: '{{ pip_packages }}'
  tags:
  - pip

- name: Install gem packages
  gem:
    name: '{{ item }}'
    state: latest
  with_items: '{{ gem_packages }}'
  tags:
  - gem
