- name: zsh - git repo for prezto fork
  git: repo=git@github.com:adamchainz/prezto.git
       dest=~/.zprezto

- name: zsh - link in prezto files
  file: state=link src=~/.zprezto/runcoms/{{ item }} path=~/.{{ item }}
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv
    - zshrc
    - zpreztorc

- name: Sublime Text 3 settings
  git: repo=git@github.com:adamchainz/sublime_text_3_settings.git
       dest=~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

- name: Dock settings
  command: defaults write com.apple.dock autohide-time-modifier -int 1
  notify: kill dock
