- name: iTerm custom settings file
  community.general.osx_defaults:
      domain: com.googlecode.iterm2
      key: PrefsCustomFolder
      type: string
      value: "{{ ansible_env.PWD }}/roles/adamgold/files"

- name: HyperSwitch custom settings file
  community.general.osx_defaults:
      domain: com.bahoom.HyperSwitch
      key: PrefsCustomFolder
      type: string
      value: "{{ ansible_env.PWD }}/roles/adamgold/files"

- name: Keymo custom settings file
  community.general.osx_defaults:
      domain: com.manytricks.Keymo
      key: PrefsCustomFolder
      type: string
      value: "{{ ansible_env.PWD }}/roles/adamgold/files"

- name: Pock custom settings file
  community.general.osx_defaults:
      domain: com.pigigaldi.pock
      key: PrefsCustomFolder
      type: string
      value: "{{ ansible_env.PWD }}/roles/adamgold/files"

- name: Notable custom settings file
  community.general.osx_defaults:
      domain: com.fabiospampinato.notable
      key: PrefsCustomFolder
      type: string
      value: "{{ ansible_env.PWD }}/roles/adamgold/files"

- name: vscode settings
  copy:
      src: "{{ ansible_env.PWD }}/roles/adamgold/files/vscode/{{ item }}"
      dest: "/Users/adamgold/Library/Application Support/Code/User/{{ item }}"
      owner: adamgold
      mode: preserve
  loop:
      - settings.json
      - keybindings.json
