- name: ssh dir stat
  stat:
      path: ~/.ssh
  register: ssh_dir

- name: ssh dir exists
  when: not ssh_dir.stat.exists
  file:
      path: ~/.ssh
      state: directory

- osx_defaults:
      key: InitialKeyRepeat
      type: int
      value: 10

- osx_defaults:
      key: KeyRepeat
      type: int
      value: 1
